# RNN

## Aplicaciones
- Detectar voz de hombre vs voz de mujer: Sequence to label
- Brain Computer Interface (BCI): Controlar una silla de ruedas. Sequence to sequence.
- Predecir la proxima palabra en funcion de las anteriores (parecido a autoencoders): No supervisado. No es Markov por que toma no solo las anteriores. Se estima lo mismo que en HMM pero sin la asumpción de que es Markov. Problema de Marov en el producto grande de muchas probabilidades pequeñas, no aparece.

In [111]:
from keras.models import Sequential
from keras.layers import LSTM, Dense
import numpy as np

In [69]:
word = ['h', 'e', 'l', 'l','o']

In [146]:
to_hot = {
             'h':[1, 0, 0, 0],
             'e':[0,1,0,0],
             'l':[0,0,1,0],
             'o':[0,0,0,1]
        }

In [147]:
data_train = np.array([to_hot[c] for c in word[:-1]]).reshape(len(word)-1,-1,len(set(word)))
labels_train = np.array([to_hot[c] for c in word[1:]]) #.reshape(len(word)-1,-1,len(set(word)))
data_train.shape, labels_train.shape
#(number_of_samples, window_size, number_of_dif_chars)
#()

((4, 1, 4), (4, 4))

In [148]:
data_train[3], labels_train[3]

(array([[0, 0, 1, 0]]), array([0, 0, 0, 1]))

In [190]:
# expected input data shape: (batch_size, timesteps, data_dim)
model = Sequential()
# input_shape=(timesteps, data_dim)
model.add(LSTM(3, input_shape=(1, 4)))
model.add(Dense(4, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='rmsprop')
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_45 (LSTM)               (None, 3)                 96        
_________________________________________________________________
dense_11 (Dense)             (None, 4)                 16        
Total params: 112
Trainable params: 112
Non-trainable params: 0
_________________________________________________________________


In [196]:
model.fit(data_train, labels_train, epochs=500, verbose=0)

In [168]:
data_train[0]

array([[1, 0, 0, 0]])

In [197]:
model.predict(data_train[0:4])

array([[ 0.09072253,  0.77222037,  0.12523173,  0.01182537],
       [ 0.01216853,  0.09912954,  0.77941167,  0.10929023],
       [ 0.00313022,  0.01961189,  0.53796566,  0.43929225],
       [ 0.00313022,  0.01961189,  0.53796566,  0.43929225]], dtype=float32)

In [204]:
# expected input data shape: (batch_size, timesteps, data_dim)
model_MLP = Sequential()
model_MLP.add(Dense(3, input_dim=4))
model_MLP.add(Dense(4, activation='softmax'))
model_MLP.compile(loss='categorical_crossentropy', optimizer='rmsprop')
model_MLP.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_19 (Dense)             (None, 3)                 15        
_________________________________________________________________
dense_20 (Dense)             (None, 4)                 16        
Total params: 31
Trainable params: 31
Non-trainable params: 0
_________________________________________________________________


In [206]:
model_MLP.fit(data_train.reshape(4,4), labels_train, epochs=500, verbose=0)

In [208]:
model_MLP.predict(data_train[0:4].reshape(4,4))

array([[ 0.0189336 ,  0.84607023,  0.12648895,  0.00850716],
       [ 0.00243876,  0.09905881,  0.84283036,  0.0556721 ],
       [ 0.01423129,  0.02748223,  0.49583361,  0.46245283],
       [ 0.01423129,  0.02748223,  0.49583361,  0.46245283]], dtype=float32)